#!/bin/bash
cd /home/ec2-user
source test/Scripts/activate
cd /home/ec2-user/frontend
curl --silent --location https://rpm.nodesource.com/setup_14.x | sudo bash -
sudo yum -y install nodejs
npm install react-router-dom@5.3.0.2.0
npm install react@18
npm run build
cd ..
pip3 install django-cors-headers==3.13.0
pip3 install djangorestframework==3.14.0
pip3 install django
pip3 install pymysql
screen -d -m python3 manage.py runserver 0.0.0.0:80

