# Generated by Django 4.1.2 on 2022-10-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donut_name', models.CharField(max_length=45)),
                ('donut_url', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'donuts',
                'managed': False,
            },
        ),
    ]
