# Generated by Django 4.1.2 on 2022-10-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_donut_delete_donuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
