# Generated by Django 4.1.2 on 2022-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_donut_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
