# Generated by Django 4.1.2 on 2022-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_donut_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donut',
            name='created',
        ),
        migrations.RemoveField(
            model_name='donut',
            name='updated',
        ),
        migrations.AlterField(
            model_name='donut',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
