# Generated by Django 4.1.2 on 2022-10-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_remove_donut_created_remove_donut_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donut',
            name='funfact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
